# Civilian
- type: startingGear
  id: TP14SettlerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLoungewear
    shoes: ClothingShoesLeather
    id: TP14SettlerIDCard
    back: ClothingBackpackSatchelLeather
    outerClothing: ClothingOuterCoatBomber
    gloves: ClothingHandsGlovesFingerless
    pocket1: FlashlightLantern
    pocket2: CrowbarRed

- type: startingGear
  id: TP14HermitGear
  equipment:
    jumpsuit: TP14ClothingUniformHardyOveralls
    shoes: ClothingShoesBootsSalvage
    back: ClothingBackpackSatchelLeather
    outerClothing: ClothingOuterCoatHermit
    suitstorage: TP14WeaponRifleEnergyRepeater

# Expeditionary
- type: startingGear
  id: TP14StepfatherGear
  equipment:
    id: SalvagePDA
    pocket1: TP14PinpointerPilot # This was commented out, not sure why. - Cookie (FatherCheese)
